# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "dwarf_images", :force => true do |t|
    t.column "dwarf_id",     :integer
    t.column "filename",     :string,   :limit => 256, :default => "", :null => false
    t.column "org_filename", :string,   :limit => 256, :default => "", :null => false
    t.column "created_at",   :datetime,                                :null => false
    t.column "updated_at",   :datetime,                                :null => false
    t.column "deleted_at",   :datetime
  end

  create_table "dwarves", :force => true do |t|
    t.column "name",       :string,   :limit => 100, :default => "", :null => false
    t.column "image_id",   :integer,                                 :null => false
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "photos", :force => true do |t|
    t.column "filename",   :string,   :limit => 256, :default => "", :null => false
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "todo_histories", :force => true do |t|
    t.column "todo_id",    :integer,                                  :null => false
    t.column "user_id",    :integer
    t.column "dwarf_id",   :integer
    t.column "message",    :string,   :limit => 2000, :default => "", :null => false
    t.column "created_at", :datetime,                                 :null => false
    t.column "updated_at", :datetime,                                 :null => false
    t.column "deleted_at", :datetime
    t.column "photo_id",   :integer
  end

  create_table "todos", :force => true do |t|
    t.column "user_id",     :integer,                                     :null => false
    t.column "todo",        :string,   :limit => 2000, :default => "",    :null => false
    t.column "finish_flag", :boolean,                  :default => false, :null => false
    t.column "deadline_at", :datetime
    t.column "created_at",  :datetime,                                    :null => false
    t.column "updated_at",  :datetime,                                    :null => false
    t.column "deleted_at",  :datetime
  end

  create_table "users", :force => true do |t|
    t.column "openid_url",  :string,   :limit => 256,  :default => "", :null => false
    t.column "livedoor_id", :string,   :limit => 1024
    t.column "hatena_id",   :string,   :limit => 1024
    t.column "nickname",    :string,   :limit => 200
    t.column "password",    :string,   :limit => 200
    t.column "created_at",  :datetime,                                 :null => false
    t.column "updated_at",  :datetime,                                 :null => false
    t.column "deleted_at",  :datetime
  end

end
